default: &default
  adapter: mysql2
  encoding: utf8mb4
  host: <%= ENV.fetch('MYSQL_HOST') %>
  port: <%= ENV.fetch('MYSQL_PORT') %>
  username: <%= ENV.fetch('MYSQL_USERNAME') %>
  password: <%= ENV.fetch('MYSQL_PASSWORD') %>

development:
  <<: *default
  database: suikoden_election_2017_development

production:
  <<: *default
  database: suikoden_election_2017_production

test:
  <<: *default
  host: 127.0.0.1
  port: 3306
  username: root
  password: root
  database: suikoden_election_2017_test
